# Site
name: 'ReadUnread'
description: 'sth. worth to be read.books,movies,stories,etc.not about share,just for practice.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'readunread'
email: 'icomesee@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Al:
      name:           Al
      site:           https://consciousnessbowl.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "我是Al，不太上进的营销人"
      email:          admin@consciousnessbowl.com
      twitter:        https://twitter.com/zuo_life

    Ex:
      name:           Ex
      site:           https://readunread.cn
      avatar:         /assets/images/avatar2.jpg
      bio:            "读书人，读书读傻了的人"
      email:          all@readunread.cn
      twitter:        https://twitter.com/he
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]