# Site
name: 'ReadUnread'
description: 'sth. worth to be read.books,movies,stories,etc.not about share,just for personal practice.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'readunread'
email: 'icomesee@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    al:
      name:           Al
      site:           https://consciousnessbowl.com
      avatar:         assets/images/al.png
      bio:            "只顾好好学习，来不及天天向上的Al"
      email:          admin@consciousnessbowl.com
      twitter:        https://twitter.com/zuo_life

    ex:
      name:           Ex
      site:           https://readunread.cn
      avatar:         assets/images/ex.jpg
      bio:            "试试读书究竟能把人读成个傻样"
      email:          all@readunread.cn
      twitter:        https://twitter.com/he
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: al
      avatar: /assets/images/al.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]